export const 
  FETCH_LISTS =  "FETCH_LISTS",
  FETCH_A_LIST = "FETCH_A_LIST",
  CREATE_LIST = "CREATE_LIST",
  CREATE_ITEM = "CREATE_ITEM",
  DELETE_LIST = "DELETE_LIST",
  DELETE_ITEM = "DELETE_ITEM"
